# Generated by Django 2.2.5 on 2019-09-24 06:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_auto_20190924_1055'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FacebookFiles',
            new_name='FacebookFile',
        ),
        migrations.RenameModel(
            old_name='GoogleFiles',
            new_name='GoogleFile',
        ),
    ]
