# Generated by Django 2.2.2 on 2019-09-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190924_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebookfile',
            name='data',
        ),
        migrations.RemoveField(
            model_name='googlefile',
            name='data',
        ),
        migrations.AddField(
            model_name='facebookfile',
            name='availible_stat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facebookfile',
            name='path_to_facebook_data',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='googlefile',
            name='availible_stat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='googlefile',
            name='path_to_google_data',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
