# Generated by Django 2.2.2 on 2019-09-25 17:06

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190925_1642'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
                ('active_objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
